favicon: null
name: suorakauppakahvi
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0
  brandStrength: 0.5531197
  lightness: 0
  brandColors:
    - '#FFFFFF'
    - '#1F1F1F'
    - '#4A5C42'
    - '#B4BDB4'
    - '#99AD27'
  rhythmicContrast: 0
typography_spectrum: 0.60503
layout_spectrum: 0.8920742
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
